name: Test Artifact Upload

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create file
        run: echo "test" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: test-artifact
          path: test.txt
